/*
  PORTFOLIO CONTENT
  -----------------
  Generated from the media in Downloads on 2026-09-13.
  Edit titles, years, tools, tags and descriptions here as the archive gets more curated.
*/

window.PORTFOLIO = {
  profile: {
    name: "Volt",
    title: "Visual Artist / Designer",
    bio: "Graphic Designer with 8+ years of experience in brand identity, merchandise design, illustration and marketing. Most of my work centres around heritage, culture and media which allows me to work on projects close to my heart and aligning with my passions.",
    email: "",
    links: []
  },

  folders: [
    { id: "all", label: "All Work", path: "~/portfolio", icon: "archive" },
    { id: "ads", label: "Ads", path: "~/portfolio/ads", icon: "folder" },
    { id: "posters", label: "Posters", path: "~/portfolio/posters", icon: "folder" },
    { id: "illustrations", label: "Illustrations", path: "~/portfolio/illustrations", icon: "folder" },
    { id: "stable-diffusion", label: "Stable Diffusion", path: "~/portfolio/stable-diffusion", icon: "folder" },
    { id: "videos", label: "Videos", path: "~/portfolio/videos", icon: "folder" }
  ],

  items: [
    {
      id: "ads-breeze-webp",
      folder: "ads",
      file: "breeze.webp",
      title: "Breeze",
      year: "2026",
      kind: "Ad",
      medium: "Advertising / Digital Design",
      tools: ["Digital"],
      tags: ["ad", "campaign", "design", "breeze"],
      description: "Breeze, archived in the ads collection.",
      thumb: "assets/thumbs/ads-breeze-webp.jpg",
      src: "assets/ads/breeze.webp"
    },
    {
      id: "ads-console-ff-webp",
      folder: "ads",
      file: "console-ff.webp",
      title: "Console FF",
      year: "2026",
      kind: "Ad",
      medium: "Advertising / Digital Design",
      tools: ["Digital"],
      tags: ["ad", "campaign", "design", "console"],
      description: "Console FF, archived in the ads collection.",
      thumb: "assets/thumbs/ads-console-ff-webp.jpg",
      src: "assets/ads/console-ff.webp"
    },
    {
      id: "ads-our-mothers-webp",
      folder: "ads",
      file: "our-mothers.webp",
      title: "Our Mothers",
      year: "2026",
      kind: "Ad",
      medium: "Advertising / Digital Design",
      tools: ["Digital"],
      tags: ["ad", "campaign", "design", "our", "mothers"],
      description: "Our Mothers, archived in the ads collection.",
      thumb: "assets/thumbs/ads-our-mothers-webp.jpg",
      src: "assets/ads/our-mothers.webp"
    },
    {
      id: "ads-revlon-final-webp",
      folder: "ads",
      file: "revlon-final.webp",
      title: "Revlon Final",
      year: "2026",
      kind: "Ad",
      medium: "Advertising / Digital Design",
      tools: ["Digital"],
      tags: ["ad", "campaign", "design", "revlon", "final"],
      description: "Revlon Final, archived in the ads collection.",
      thumb: "assets/thumbs/ads-revlon-final-webp.jpg",
      src: "assets/ads/revlon-final.webp"
    },
    {
      id: "videos-2022-03-05-2-1-avi",
      folder: "videos",
      file: "2022-03-05-2-1.avi",
      title: "2022 03 05 (2) 1",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "2022"],
      description: "2022 03 05 (2) 1 is archived as a source AVI and should be converted or hosted externally before publishing.",
      thumb: "",
      video: "",
      embed: ""
    },
    {
      id: "videos-arthur-waves-1-mp4",
      folder: "videos",
      file: "arthur-waves-1.mp4",
      title: "A1111 Wave Animation",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "arthur", "waves"],
      description: "A1111 Wave Animation, archived in the videos collection.",
      thumb: "assets/thumbs/videos-arthur-waves-1-mp4.jpg",
      video: "assets/videos/arthur-waves-1.mp4",
      embed: ""
    },
    {
      id: "videos-capucine-augustus-mov",
      folder: "videos",
      file: "capucine-augustus.mov",
      title: "Capucine and Augustus Collage Animation",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "capucine", "augustus"],
      description: "Capucine and Augustus Collage Animation, archived in the videos collection.",
      thumb: "assets/thumbs/videos-capucine-augustus-mov.jpg",
      video: "assets/videos/capucine-augustus.mov",
      embed: ""
    },
    {
      id: "videos-forest1-mp4",
      folder: "videos",
      file: "forest1.mp4",
      title: "A1111 Forest Animation",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "forest1"],
      description: "A1111 Forest Animation, archived in the videos collection.",
      thumb: "assets/thumbs/videos-forest1-mp4.jpg",
      video: "assets/videos/forest1.mp4",
      embed: ""
    },
    {
      id: "videos-img-2691-mov",
      folder: "videos",
      file: "IMG_2691.mp4",
      title: "Enheduanna Short Historical Documentary",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "img", "2691"],
      description: "Enheduanna Short Historical Documentary, archived in the videos collection.",
      thumb: "assets/thumbs/videos-img-2691-mov.jpg",
      video: "assets/videos/IMG_2691.mp4",
      embed: ""
    },
    {
      id: "videos-img-2693-mov",
      folder: "videos",
      file: "IMG_2693.mp4",
      title: "The Fall Vertical Shot Cinematography",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "img", "2693"],
      description: "The Fall Vertical Shot Cinematography, archived in the videos collection.",
      thumb: "assets/thumbs/videos-img-2693-mov.jpg",
      video: "assets/videos/IMG_2693.mp4",
      embed: ""
    },
    {
      id: "videos-img-2697-mp4",
      folder: "videos",
      file: "IMG_2697 (1).mp4",
      title: "Lawrence of Arabia Vertical Shot Cinematography",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "img", "2697"],
      description: "Lawrence of Arabia Vertical Shot Cinematography, archived in the videos collection.",
      thumb: "assets/thumbs/videos-img-2697-mp4.jpg",
      video: "assets/videos/IMG_2697 (1).mp4",
      embed: ""
    },
    {
      id: "videos-patrician-mp4",
      folder: "videos",
      file: "patrician.mp4",
      title: "Patrician Pixel Animation",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "patrician"],
      description: "Patrician Pixel Animation, archived in the videos collection.",
      thumb: "assets/thumbs/videos-patrician-mp4.jpg",
      video: "assets/videos/patrician.mp4",
      embed: ""
    },
    {
      id: "videos-w1-mp4",
      folder: "videos",
      file: "w1.mp4",
      title: "A1111 Woman Animation",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion"],
      description: "A1111 Woman Animation, archived in the videos collection.",
      thumb: "assets/thumbs/videos-w1-mp4.jpg",
      video: "assets/videos/w1.mp4",
      embed: ""
    },
    {
      id: "videos-wow-mp4",
      folder: "videos",
      file: "wow.mp4",
      title: "A1111 Experimental Animation",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "wow"],
      description: "A1111 Experimental Animation, archived in the videos collection.",
      thumb: "assets/thumbs/videos-wow-mp4.jpg",
      video: "assets/videos/wow.mp4",
      embed: ""
    },
    {
      id: "illustrations-augustus-mb-webp",
      folder: "illustrations",
      file: "augustus-mb.webp",
      title: "Augustus Caesar Matchbox Illustration, First in the Collection",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "augustus"],
      description: "Augustus Caesar Matchbox Illustration, First in the Collection, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-augustus-mb-webp.jpg",
      src: "assets/illustrations/augustus-mb.webp"
    },
    {
      id: "illustrations-cap-halo-webp",
      folder: "illustrations",
      file: "cap-halo.webp",
      title: "Capucine Fashion Illustration",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "cap", "halo"],
      description: "Capucine Fashion Illustration, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-cap-halo-webp.jpg",
      src: "assets/illustrations/cap-halo.webp"
    },
    {
      id: "illustrations-capucine-jpg",
      folder: "illustrations",
      file: "capucine.jpg",
      title: "Capucine Pop Art Illustration",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "capucine"],
      description: "Capucine Pop Art Illustration, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-capucine-jpg.jpg",
      src: "assets/illustrations/capucine.jpg"
    },
    {
      id: "illustrations-capucine-png",
      folder: "illustrations",
      file: "capucine.png",
      title: "Capucine Digital Matrix Illustration",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "capucine"],
      description: "Capucine Digital Matrix Illustration, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-capucine-png.jpg",
      src: "assets/illustrations/capucine.png"
    },
    {
      id: "illustrations-green-kirtle-jpg",
      folder: "illustrations",
      file: "green-kirtle.jpg",
      title: "Lady of the Green Kirtle Pixel Art",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "green", "kirtle"],
      description: "Lady of the Green Kirtle Pixel Art, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-green-kirtle-jpg.jpg",
      src: "assets/illustrations/green-kirtle.jpg"
    },
    {
      id: "illustrations-livia-webp",
      folder: "illustrations",
      file: "livia.webp",
      title: "Livia Drusilla Matchbox Illustration, First in the Collection",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "livia"],
      description: "Livia Drusilla Matchbox Illustration, First in the Collection, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-livia-webp.jpg",
      src: "assets/illustrations/livia.webp"
    },
    {
      id: "illustrations-meskalamdug-webp",
      folder: "illustrations",
      file: "meskalamdug.webp",
      title: "Sumerian King Meskalamdug Historical Illustration",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "meskalamdug"],
      description: "Sumerian King Meskalamdug Historical Illustration, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-meskalamdug-webp.jpg",
      src: "assets/illustrations/meskalamdug.webp"
    },
    {
      id: "illustrations-monica-png",
      folder: "illustrations",
      file: "monica.png",
      title: "Monica Bellucci Abstract Illustration",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "monica"],
      description: "Monica Bellucci Abstract Illustration, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-monica-png.jpg",
      src: "assets/illustrations/monica.png"
    },
    {
      id: "illustrations-moonbeamstudy-jpg",
      folder: "illustrations",
      file: "moonbeamstudy.jpg",
      title: "Moonbeam Illustration",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "moonbeamstudy"],
      description: "Moonbeam Illustration, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-moonbeamstudy-jpg.jpg",
      src: "assets/illustrations/moonbeamstudy.jpg"
    },
    {
      id: "illustrations-nft1-jpg",
      folder: "illustrations",
      file: "nft1.jpg",
      title: "Acid Tears Pixel Art",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "nft1"],
      description: "Acid Tears Pixel Art, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-nft1-jpg.jpg",
      src: "assets/illustrations/nft1.jpg"
    },
    {
      id: "illustrations-nft2-jpg",
      folder: "illustrations",
      file: "nft2.jpg",
      title: "Arming Sword in Glass Case Pixel Art",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "nft2"],
      description: "Arming Sword in Glass Case Pixel Art, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-nft2-jpg.jpg",
      src: "assets/illustrations/nft2.jpg"
    },
    {
      id: "illustrations-or-webp",
      folder: "illustrations",
      file: "or.webp",
      title: "Ousama-Ranking Anime Illustration 01",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital"],
      description: "Ousama-Ranking Anime Illustration 01, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-or-webp.jpg",
      src: "assets/illustrations/or.webp"
    },
    {
      id: "illustrations-untitled-design-2-webp",
      folder: "illustrations",
      file: "untitled-design-2.webp",
      title: "Ousama-Ranking Anime Illustration 02",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "untitled", "design"],
      description: "Ousama-Ranking Anime Illustration 02, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-untitled-design-2-webp.jpg",
      src: "assets/illustrations/untitled-design-2.webp"
    },
    {
      id: "illustrations-xena-jpg",
      folder: "illustrations",
      file: "xena.jpg",
      title: "Xena Warrior Princess Illustration",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "xena"],
      description: "Xena Warrior Princess Illustration, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-xena-jpg.jpg",
      src: "assets/illustrations/xena.jpg"
    },
    {
      id: "illustrations-yuliastudy-jpg",
      folder: "illustrations",
      file: "yuliastudy.jpg",
      title: "Yulia Snigir Pop Art Illustration",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "yuliastudy"],
      description: "Yulia Snigir Pop Art Illustration, archived in the illustrations collection.",
      thumb: "assets/thumbs/illustrations-yuliastudy-jpg.jpg",
      src: "assets/illustrations/yuliastudy.jpg"
    },
    {
      id: "posters-baylan-skoll-red-webp",
      folder: "posters",
      file: "baylan-skoll-red.webp",
      title: "Ahsoka Baylan Skoll Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "baylan", "skoll", "red"],
      description: "Ahsoka Baylan Skoll Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-baylan-skoll-red-webp.jpg",
      src: "assets/posters/baylan-skoll-red.webp"
    },
    {
      id: "posters-blue-eye-webp",
      folder: "posters",
      file: "blue-eye.webp",
      title: "Mizu Blue Samurai Anime Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "blue", "eye"],
      description: "Mizu Blue Samurai Anime Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-blue-eye-webp.jpg",
      src: "assets/posters/blue-eye.webp"
    },
    {
      id: "posters-cap-3-webp",
      folder: "posters",
      file: "cap-3.webp",
      title: "Capucine Collage Art",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "cap"],
      description: "Capucine Collage Art, archived in the posters collection.",
      thumb: "assets/thumbs/posters-cap-3-webp.jpg",
      src: "assets/posters/cap-3.webp"
    },
    {
      id: "posters-cap-4-webp",
      folder: "posters",
      file: "cap-4.webp",
      title: "Capucine Linear Poster 01",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "cap"],
      description: "Capucine Linear Poster 01, archived in the posters collection.",
      thumb: "assets/thumbs/posters-cap-4-webp.jpg",
      src: "assets/posters/cap-4.webp"
    },
    {
      id: "posters-cap-monitor-webp",
      folder: "posters",
      file: "cap-monitor.webp",
      title: "Capucine Linear Poster 02",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "cap", "monitor"],
      description: "Capucine Linear Poster 02, archived in the posters collection.",
      thumb: "assets/thumbs/posters-cap-monitor-webp.jpg",
      src: "assets/posters/cap-monitor.webp"
    },
    {
      id: "posters-cap-jpg",
      folder: "posters",
      file: "cap.jpg",
      title: "Capucine Fellini Satyricon Digital Matrix Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "cap"],
      description: "Capucine Fellini Satyricon Digital Matrix Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-cap-jpg.jpg",
      src: "assets/posters/cap.jpg"
    },
    {
      id: "posters-capucine-reel-jpg",
      folder: "posters",
      file: "capucine-reel.jpg",
      title: "Capucine Abstract Collage",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "capucine", "reel"],
      description: "Capucine Abstract Collage, archived in the posters collection.",
      thumb: "assets/thumbs/posters-capucine-reel-jpg.jpg",
      src: "assets/posters/capucine-reel.jpg"
    },
    {
      id: "posters-carmilla-b-webp",
      folder: "posters",
      file: "carmilla-b.webp",
      title: "Carmilla Castlevania Anime Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "carmilla"],
      description: "Carmilla Castlevania Anime Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-carmilla-b-webp.jpg",
      src: "assets/posters/carmilla-b.webp"
    },
    {
      id: "posters-empire-upscale-webp",
      folder: "posters",
      file: "empire-upscale.webp",
      title: "Apple TV's Foundation Brother Day Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "empire", "upscale"],
      description: "Apple TV's Foundation Brother Day Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-empire-upscale-webp.jpg",
      src: "assets/posters/empire-upscale.webp"
    },
    {
      id: "posters-enoch-webp",
      folder: "posters",
      file: "enoch.webp",
      title: "Ahsoka Enoch Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "enoch"],
      description: "Ahsoka Enoch Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-enoch-webp.jpg",
      src: "assets/posters/enoch.webp"
    },
    {
      id: "posters-gladiator-border-webp",
      folder: "posters",
      file: "gladiator-border.webp",
      title: "Gladiator Film Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "gladiator", "border"],
      description: "Gladiator Film Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-gladiator-border-webp.jpg",
      src: "assets/posters/gladiator-border.webp"
    },
    {
      id: "posters-gustave-webp",
      folder: "posters",
      file: "gustave.webp",
      title: "Grand Budapest Hotel Gustave Film Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "gustave"],
      description: "Grand Budapest Hotel Gustave Film Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-gustave-webp.jpg",
      src: "assets/posters/gustave.webp"
    },
    {
      id: "posters-hand-tb-webp",
      folder: "posters",
      file: "hand-tb.webp",
      title: "Capucine Retro Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "hand"],
      description: "Capucine Retro Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-hand-tb-webp.jpg",
      src: "assets/posters/hand-tb.webp"
    },
    {
      id: "posters-kane-webp",
      folder: "posters",
      file: "kane.webp",
      title: "Harry Kane England Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "kane"],
      description: "Harry Kane England Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-kane-webp.jpg",
      src: "assets/posters/kane.webp"
    },
    {
      id: "posters-loa-1-webp",
      folder: "posters",
      file: "loa-1.webp",
      title: "Lawrence of Arabia Film Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "loa"],
      description: "Lawrence of Arabia Film Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-loa-1-webp.jpg",
      src: "assets/posters/loa-1.webp"
    },
    {
      id: "posters-monster-munch-jpg",
      folder: "posters",
      file: "monster-munch.jpg",
      title: "Monster Munch Collage Art",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "monster", "munch"],
      description: "Monster Munch Collage Art, archived in the posters collection.",
      thumb: "assets/thumbs/posters-monster-munch-jpg.jpg",
      src: "assets/posters/monster-munch.jpg"
    },
    {
      id: "posters-palms-intertwined-webp",
      folder: "posters",
      file: "palms-intertwined.webp",
      title: "Collage Art 01",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "palms", "intertwined"],
      description: "Collage Art 01, archived in the posters collection.",
      thumb: "assets/thumbs/posters-palms-intertwined-webp.jpg",
      src: "assets/posters/palms-intertwined.webp"
    },
    {
      id: "posters-sarah-walker-webp",
      folder: "posters",
      file: "sarah-walker.webp",
      title: "Chuck Sarah Walker Retro Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "sarah", "walker"],
      description: "Chuck Sarah Walker Retro Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-sarah-walker-webp.jpg",
      src: "assets/posters/sarah-walker.webp"
    },
    {
      id: "posters-solo-fel-card-webp",
      folder: "posters",
      file: "solo-fel-card.webp",
      title: "Original Card Design",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "solo", "fel", "card"],
      description: "Original Card Design, archived in the posters collection.",
      thumb: "assets/thumbs/posters-solo-fel-card-webp.jpg",
      src: "assets/posters/solo-fel-card.webp"
    },
    {
      id: "posters-stars-texture3-webp",
      folder: "posters",
      file: "stars-texture3.webp",
      title: "Celestial Occult Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "stars", "texture3"],
      description: "Celestial Occult Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-stars-texture3-webp.jpg",
      src: "assets/posters/stars-texture3.webp"
    },
    {
      id: "posters-thbs-png",
      folder: "posters",
      file: "thbs.png",
      title: "Metal Gear Solid the Boss",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "thbs"],
      description: "Metal Gear Solid the Boss, archived in the posters collection.",
      thumb: "assets/thumbs/posters-thbs-png.jpg",
      src: "assets/posters/thbs.png"
    },
    {
      id: "posters-the-7th-dawn-webp",
      folder: "posters",
      file: "the-7th-dawn.webp",
      title: "The 7th Dawn Capucine Film Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "the", "7th", "dawn"],
      description: "The 7th Dawn Capucine Film Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-the-7th-dawn-webp.jpg",
      src: "assets/posters/the-7th-dawn.webp"
    },
    {
      id: "posters-the-eye-jpg",
      folder: "posters",
      file: "the-eye.jpg",
      title: "Collage Art 02",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "the", "eye"],
      description: "Collage Art 02, archived in the posters collection.",
      thumb: "assets/thumbs/posters-the-eye-jpg.jpg",
      src: "assets/posters/the-eye.jpg"
    },
    {
      id: "posters-vhd-webp",
      folder: "posters",
      file: "vhd.webp",
      title: "Vampire Hunter D Poster",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "vhd"],
      description: "Vampire Hunter D Poster, archived in the posters collection.",
      thumb: "assets/thumbs/posters-vhd-webp.jpg",
      src: "assets/posters/vhd.webp"
    },
    {
      id: "stable-diffusion-cap18-png",
      folder: "stable-diffusion",
      file: "cap18.png",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 01",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "cap18"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 01, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-cap18-png.jpg",
      src: "assets/stable-diffusion/cap18.png"
    },
    {
      id: "stable-diffusion-cap28-png",
      folder: "stable-diffusion",
      file: "cap28.png",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 02",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "cap28"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 02, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-cap28-png.jpg",
      src: "assets/stable-diffusion/cap28.png"
    },
    {
      id: "stable-diffusion-face-close-up-of-aqu-jpg",
      folder: "stable-diffusion",
      file: "face-close-up-of-aqu.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 03",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "face", "close", "aqu"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 03, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-face-close-up-of-aqu-jpg.jpg",
      src: "assets/stable-diffusion/face-close-up-of-aqu.jpg"
    },
    {
      id: "stable-diffusion-face-close-up-of-bat-1-jpg",
      folder: "stable-diffusion",
      file: "face-close-up-of-bat-1.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 04",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "face", "close", "bat"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 04, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-face-close-up-of-bat-1-jpg.jpg",
      src: "assets/stable-diffusion/face-close-up-of-bat-1.jpg"
    },
    {
      id: "stable-diffusion-face-close-up-of-sup-jpg",
      folder: "stable-diffusion",
      file: "face-close-up-of-sup.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 05",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "face", "close", "sup"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 05, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-face-close-up-of-sup-jpg.jpg",
      src: "assets/stable-diffusion/face-close-up-of-sup.jpg"
    },
    {
      id: "stable-diffusion-gilgamesh-brush-transformed-upscayl-4x-realesrgan-x4plus-anime-jpeg",
      folder: "stable-diffusion",
      file: "gilgamesh-brush-transformed-upscayl-4x-realesrgan-x4plus-anime.jpeg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 06",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "gilgamesh", "brush", "transformed"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 06, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-gilgamesh-brush-transformed-upscayl-4x-realesrgan-x4plus-anime-jpeg.jpg",
      src: "assets/stable-diffusion/gilgamesh-brush-transformed-upscayl-4x-realesrgan-x4plus-anime.jpeg"
    },
    {
      id: "stable-diffusion-hen-jpg",
      folder: "stable-diffusion",
      file: "hen.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 07",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "hen"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 07, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-hen-jpg.jpg",
      src: "assets/stable-diffusion/hen.jpg"
    },
    {
      id: "stable-diffusion-hero1-jpg",
      folder: "stable-diffusion",
      file: "hero1.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 08",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "hero1"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 08, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-hero1-jpg.jpg",
      src: "assets/stable-diffusion/hero1.jpg"
    },
    {
      id: "stable-diffusion-hero3-jpg",
      folder: "stable-diffusion",
      file: "hero3.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 09",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "hero3"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 09, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-hero3-jpg.jpg",
      src: "assets/stable-diffusion/hero3.jpg"
    },
    {
      id: "stable-diffusion-myth1-jpg",
      folder: "stable-diffusion",
      file: "myth1.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 10",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "myth1"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 10, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-myth1-jpg.jpg",
      src: "assets/stable-diffusion/myth1.jpg"
    },
    {
      id: "stable-diffusion-myth2-jpg",
      folder: "stable-diffusion",
      file: "myth2.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 11",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "myth2"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 11, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-myth2-jpg.jpg",
      src: "assets/stable-diffusion/myth2.jpg"
    },
    {
      id: "stable-diffusion-nov-1-jpg",
      folder: "stable-diffusion",
      file: "nov-1.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 12",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "nov"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 12, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-nov-1-jpg.jpg",
      src: "assets/stable-diffusion/nov-1.jpg"
    },
    {
      id: "stable-diffusion-nov-2-jpg",
      folder: "stable-diffusion",
      file: "nov-2.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 13",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "nov"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 13, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-nov-2-jpg.jpg",
      src: "assets/stable-diffusion/nov-2.jpg"
    },
    {
      id: "stable-diffusion-nov-3-jpg",
      folder: "stable-diffusion",
      file: "nov-3.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 14",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "nov"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 14, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-nov-3-jpg.jpg",
      src: "assets/stable-diffusion/nov-3.jpg"
    },
    {
      id: "stable-diffusion-nov-4-png",
      folder: "stable-diffusion",
      file: "nov-4.png",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 15",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "nov"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 15, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-nov-4-png.jpg",
      src: "assets/stable-diffusion/nov-4.png"
    },
    {
      id: "stable-diffusion-sf2-jpg",
      folder: "stable-diffusion",
      file: "sf2.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 16",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "sf2"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 16, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-sf2-jpg.jpg",
      src: "assets/stable-diffusion/sf2.jpg"
    },
    {
      id: "stable-diffusion-sf3-jpg",
      folder: "stable-diffusion",
      file: "sf3.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 17",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "sf3"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 17, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-sf3-jpg.jpg",
      src: "assets/stable-diffusion/sf3.jpg"
    },
    {
      id: "stable-diffusion-supe18-jpg",
      folder: "stable-diffusion",
      file: "supe18.jpg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 18",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "supe18"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 18, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-supe18-jpg.jpg",
      src: "assets/stable-diffusion/supe18.jpg"
    },
    {
      id: "stable-diffusion-thor-jpeg",
      folder: "stable-diffusion",
      file: "thor.jpeg",
      title: "Golden Age of Illustration Trained Stable Diffusion Model Output 19",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "thor"],
      description: "Golden Age of Illustration Trained Stable Diffusion Model Output 19, archived in the stable diffusion collection.",
      thumb: "assets/thumbs/stable-diffusion-thor-jpeg.jpg",
      src: "assets/stable-diffusion/thor.jpeg"
    }
  ]
};
