/*
  PORTFOLIO CONTENT
  -----------------
  Generated from the media in Downloads on 2026-09-13.
  Edit titles, years, tools, tags and descriptions here as the archive gets more curated.
*/

window.PORTFOLIO = {
  profile: {
    name: "Volt",
    title: "Visual Artist / Designer",
    bio: "A selected archive of ads, posters, illustrations, AI studies and moving-image work.",
    email: "",
    links: []
  },

  folders: [
    { id: "all", label: "All Work", path: "~/portfolio", icon: "archive" },
    { id: "ads", label: "Ads", path: "~/portfolio/ads", icon: "folder" },
    { id: "posters", label: "Posters", path: "~/portfolio/posters", icon: "folder" },
    { id: "illustrations", label: "Illustrations", path: "~/portfolio/illustrations", icon: "folder" },
    { id: "stable-diffusion", label: "Stable Diffusion", path: "~/portfolio/stable-diffusion", icon: "folder" },
    { id: "videos", label: "Videos", path: "~/portfolio/videos", icon: "folder" }
  ],

  items: [
    {
      id: "ads-breeze-webp",
      folder: "ads",
      file: "breeze.webp",
      title: "Breeze",
      year: "2026",
      kind: "Ad",
      medium: "Advertising / Digital Design",
      tools: ["Digital"],
      tags: ["ad", "campaign", "design", "breeze"],
      description: "Breeze, archived in the ads collection.",
      thumb: "assets/ads/breeze.webp",
      src: "assets/ads/breeze.webp"
    },
    {
      id: "ads-console-ff-webp",
      folder: "ads",
      file: "console-ff.webp",
      title: "Console Ff",
      year: "2026",
      kind: "Ad",
      medium: "Advertising / Digital Design",
      tools: ["Digital"],
      tags: ["ad", "campaign", "design", "console"],
      description: "Console Ff, archived in the ads collection.",
      thumb: "assets/ads/console-ff.webp",
      src: "assets/ads/console-ff.webp"
    },
    {
      id: "ads-our-mothers-webp",
      folder: "ads",
      file: "our-mothers.webp",
      title: "Our Mothers",
      year: "2026",
      kind: "Ad",
      medium: "Advertising / Digital Design",
      tools: ["Digital"],
      tags: ["ad", "campaign", "design", "our", "mothers"],
      description: "Our Mothers, archived in the ads collection.",
      thumb: "assets/ads/our-mothers.webp",
      src: "assets/ads/our-mothers.webp"
    },
    {
      id: "ads-revlon-final-webp",
      folder: "ads",
      file: "revlon-final.webp",
      title: "Revlon Final",
      year: "2026",
      kind: "Ad",
      medium: "Advertising / Digital Design",
      tools: ["Digital"],
      tags: ["ad", "campaign", "design", "revlon", "final"],
      description: "Revlon Final, archived in the ads collection.",
      thumb: "assets/ads/revlon-final.webp",
      src: "assets/ads/revlon-final.webp"
    },
    {
      id: "videos-2022-03-05-2-1-avi",
      folder: "videos",
      file: "2022-03-05-2-1.avi",
      title: "2022 03 05 (2) 1",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "2022"],
      description: "2022 03 05 (2) 1, archived in the videos collection.",
      thumb: "",
      video: "assets/videos/2022-03-05-2-1.avi",
      embed: ""
    },
    {
      id: "videos-arthur-waves-1-mp4",
      folder: "videos",
      file: "arthur-waves-1.mp4",
      title: "Arthur Waves 1",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "arthur", "waves"],
      description: "Arthur Waves 1, archived in the videos collection.",
      thumb: "",
      video: "assets/videos/arthur-waves-1.mp4",
      embed: ""
    },
    {
      id: "videos-capucine-augustus-mov",
      folder: "videos",
      file: "capucine-augustus.mov",
      title: "Capucine Augustus",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "capucine", "augustus"],
      description: "Capucine Augustus, archived in the videos collection.",
      thumb: "",
      video: "assets/videos/capucine-augustus.mov",
      embed: ""
    },
    {
      id: "videos-forest1-mp4",
      folder: "videos",
      file: "forest1.mp4",
      title: "Forest1",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "forest1"],
      description: "Forest1, archived in the videos collection.",
      thumb: "",
      video: "assets/videos/forest1.mp4",
      embed: ""
    },
    {
      id: "videos-img-2691-mov",
      folder: "videos",
      file: "img-2691.mov",
      title: "Img 2691",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "img", "2691"],
      description: "Img 2691, archived in the videos collection.",
      thumb: "",
      video: "assets/videos/img-2691.mov",
      embed: ""
    },
    {
      id: "videos-img-2693-mov",
      folder: "videos",
      file: "img-2693.mov",
      title: "Img 2693",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "img", "2693"],
      description: "Img 2693, archived in the videos collection.",
      thumb: "",
      video: "assets/videos/img-2693.mov",
      embed: ""
    },
    {
      id: "videos-img-2697-mp4",
      folder: "videos",
      file: "img-2697.mp4",
      title: "Img 2697",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "img", "2697"],
      description: "Img 2697, archived in the videos collection.",
      thumb: "",
      video: "assets/videos/img-2697.mp4",
      embed: ""
    },
    {
      id: "videos-patrician-mp4",
      folder: "videos",
      file: "patrician.mp4",
      title: "Patrician",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "patrician"],
      description: "Patrician, archived in the videos collection.",
      thumb: "",
      video: "assets/videos/patrician.mp4",
      embed: ""
    },
    {
      id: "videos-w1-mp4",
      folder: "videos",
      file: "w1.mp4",
      title: "W1",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion"],
      description: "W1, archived in the videos collection.",
      thumb: "",
      video: "assets/videos/w1.mp4",
      embed: ""
    },
    {
      id: "videos-wow-mp4",
      folder: "videos",
      file: "wow.mp4",
      title: "Wow",
      year: "2026",
      kind: "Video",
      medium: "Animation / Motion",
      tools: ["Digital"],
      tags: ["video", "animation", "motion", "wow"],
      description: "Wow, archived in the videos collection.",
      thumb: "",
      video: "assets/videos/wow.mp4",
      embed: ""
    },
    {
      id: "illustrations-augustus-mb-webp",
      folder: "illustrations",
      file: "augustus-mb.webp",
      title: "Augustus Mb",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "augustus"],
      description: "Augustus Mb, archived in the illustrations collection.",
      thumb: "assets/illustrations/augustus-mb.webp",
      src: "assets/illustrations/augustus-mb.webp"
    },
    {
      id: "illustrations-cap-halo-webp",
      folder: "illustrations",
      file: "cap-halo.webp",
      title: "Cap Halo",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "cap", "halo"],
      description: "Cap Halo, archived in the illustrations collection.",
      thumb: "assets/illustrations/cap-halo.webp",
      src: "assets/illustrations/cap-halo.webp"
    },
    {
      id: "illustrations-capucine-jpg",
      folder: "illustrations",
      file: "capucine.jpg",
      title: "Capucine",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "capucine"],
      description: "Capucine, archived in the illustrations collection.",
      thumb: "assets/illustrations/capucine.jpg",
      src: "assets/illustrations/capucine.jpg"
    },
    {
      id: "illustrations-capucine-png",
      folder: "illustrations",
      file: "capucine.png",
      title: "Capucine",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "capucine"],
      description: "Capucine, archived in the illustrations collection.",
      thumb: "assets/illustrations/capucine.png",
      src: "assets/illustrations/capucine.png"
    },
    {
      id: "illustrations-green-kirtle-jpg",
      folder: "illustrations",
      file: "green-kirtle.jpg",
      title: "Green Kirtle",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "green", "kirtle"],
      description: "Green Kirtle, archived in the illustrations collection.",
      thumb: "assets/illustrations/green-kirtle.jpg",
      src: "assets/illustrations/green-kirtle.jpg"
    },
    {
      id: "illustrations-livia-webp",
      folder: "illustrations",
      file: "livia.webp",
      title: "Livia",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "livia"],
      description: "Livia, archived in the illustrations collection.",
      thumb: "assets/illustrations/livia.webp",
      src: "assets/illustrations/livia.webp"
    },
    {
      id: "illustrations-meskalamdug-webp",
      folder: "illustrations",
      file: "meskalamdug.webp",
      title: "Meskalamdug",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "meskalamdug"],
      description: "Meskalamdug, archived in the illustrations collection.",
      thumb: "assets/illustrations/meskalamdug.webp",
      src: "assets/illustrations/meskalamdug.webp"
    },
    {
      id: "illustrations-monica-png",
      folder: "illustrations",
      file: "monica.png",
      title: "Monica",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "monica"],
      description: "Monica, archived in the illustrations collection.",
      thumb: "assets/illustrations/monica.png",
      src: "assets/illustrations/monica.png"
    },
    {
      id: "illustrations-moonbeamstudy-jpg",
      folder: "illustrations",
      file: "moonbeamstudy.jpg",
      title: "Moonbeamstudy",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "moonbeamstudy"],
      description: "Moonbeamstudy, archived in the illustrations collection.",
      thumb: "assets/illustrations/moonbeamstudy.jpg",
      src: "assets/illustrations/moonbeamstudy.jpg"
    },
    {
      id: "illustrations-nft1-jpg",
      folder: "illustrations",
      file: "nft1.jpg",
      title: "Nft1",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "nft1"],
      description: "Nft1, archived in the illustrations collection.",
      thumb: "assets/illustrations/nft1.jpg",
      src: "assets/illustrations/nft1.jpg"
    },
    {
      id: "illustrations-nft2-jpg",
      folder: "illustrations",
      file: "nft2.jpg",
      title: "Nft2",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "nft2"],
      description: "Nft2, archived in the illustrations collection.",
      thumb: "assets/illustrations/nft2.jpg",
      src: "assets/illustrations/nft2.jpg"
    },
    {
      id: "illustrations-or-webp",
      folder: "illustrations",
      file: "or.webp",
      title: "Or",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital"],
      description: "Or, archived in the illustrations collection.",
      thumb: "assets/illustrations/or.webp",
      src: "assets/illustrations/or.webp"
    },
    {
      id: "illustrations-untitled-design-2-webp",
      folder: "illustrations",
      file: "untitled-design-2.webp",
      title: "Untitled Design(2)",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "untitled", "design"],
      description: "Untitled Design(2), archived in the illustrations collection.",
      thumb: "assets/illustrations/untitled-design-2.webp",
      src: "assets/illustrations/untitled-design-2.webp"
    },
    {
      id: "illustrations-xena-jpg",
      folder: "illustrations",
      file: "xena.jpg",
      title: "Xena",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "xena"],
      description: "Xena, archived in the illustrations collection.",
      thumb: "assets/illustrations/xena.jpg",
      src: "assets/illustrations/xena.jpg"
    },
    {
      id: "illustrations-yuliastudy-jpg",
      folder: "illustrations",
      file: "yuliastudy.jpg",
      title: "Yuliastudy",
      year: "2026",
      kind: "Illustration",
      medium: "Digital Illustration",
      tools: ["Digital"],
      tags: ["illustration", "character", "digital", "yuliastudy"],
      description: "Yuliastudy, archived in the illustrations collection.",
      thumb: "assets/illustrations/yuliastudy.jpg",
      src: "assets/illustrations/yuliastudy.jpg"
    },
    {
      id: "posters-baylan-skoll-red-webp",
      folder: "posters",
      file: "baylan-skoll-red.webp",
      title: "Baylan Skoll Red",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "baylan", "skoll", "red"],
      description: "Baylan Skoll Red, archived in the posters collection.",
      thumb: "assets/posters/baylan-skoll-red.webp",
      src: "assets/posters/baylan-skoll-red.webp"
    },
    {
      id: "posters-blue-eye-webp",
      folder: "posters",
      file: "blue-eye.webp",
      title: "Blue Eye",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "blue", "eye"],
      description: "Blue Eye, archived in the posters collection.",
      thumb: "assets/posters/blue-eye.webp",
      src: "assets/posters/blue-eye.webp"
    },
    {
      id: "posters-cap-3-webp",
      folder: "posters",
      file: "cap-3.webp",
      title: "Cap 3",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "cap"],
      description: "Cap 3, archived in the posters collection.",
      thumb: "assets/posters/cap-3.webp",
      src: "assets/posters/cap-3.webp"
    },
    {
      id: "posters-cap-4-webp",
      folder: "posters",
      file: "cap-4.webp",
      title: "Cap 4",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "cap"],
      description: "Cap 4, archived in the posters collection.",
      thumb: "assets/posters/cap-4.webp",
      src: "assets/posters/cap-4.webp"
    },
    {
      id: "posters-cap-monitor-webp",
      folder: "posters",
      file: "cap-monitor.webp",
      title: "Cap Monitor",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "cap", "monitor"],
      description: "Cap Monitor, archived in the posters collection.",
      thumb: "assets/posters/cap-monitor.webp",
      src: "assets/posters/cap-monitor.webp"
    },
    {
      id: "posters-cap-jpg",
      folder: "posters",
      file: "cap.jpg",
      title: "Cap",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "cap"],
      description: "Cap, archived in the posters collection.",
      thumb: "assets/posters/cap.jpg",
      src: "assets/posters/cap.jpg"
    },
    {
      id: "posters-capucine-reel-jpg",
      folder: "posters",
      file: "capucine-reel.jpg",
      title: "Capucine Reel",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "capucine", "reel"],
      description: "Capucine Reel, archived in the posters collection.",
      thumb: "assets/posters/capucine-reel.jpg",
      src: "assets/posters/capucine-reel.jpg"
    },
    {
      id: "posters-carmilla-b-webp",
      folder: "posters",
      file: "carmilla-b.webp",
      title: "Carmilla B",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "carmilla"],
      description: "Carmilla B, archived in the posters collection.",
      thumb: "assets/posters/carmilla-b.webp",
      src: "assets/posters/carmilla-b.webp"
    },
    {
      id: "posters-empire-upscale-webp",
      folder: "posters",
      file: "empire-upscale.webp",
      title: "Empire Upscale",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "empire", "upscale"],
      description: "Empire Upscale, archived in the posters collection.",
      thumb: "assets/posters/empire-upscale.webp",
      src: "assets/posters/empire-upscale.webp"
    },
    {
      id: "posters-enoch-webp",
      folder: "posters",
      file: "enoch.webp",
      title: "Enoch",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "enoch"],
      description: "Enoch, archived in the posters collection.",
      thumb: "assets/posters/enoch.webp",
      src: "assets/posters/enoch.webp"
    },
    {
      id: "posters-gladiator-border-webp",
      folder: "posters",
      file: "gladiator-border.webp",
      title: "Gladiator Border",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "gladiator", "border"],
      description: "Gladiator Border, archived in the posters collection.",
      thumb: "assets/posters/gladiator-border.webp",
      src: "assets/posters/gladiator-border.webp"
    },
    {
      id: "posters-gustave-webp",
      folder: "posters",
      file: "gustave.webp",
      title: "Gustave",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "gustave"],
      description: "Gustave, archived in the posters collection.",
      thumb: "assets/posters/gustave.webp",
      src: "assets/posters/gustave.webp"
    },
    {
      id: "posters-hand-tb-webp",
      folder: "posters",
      file: "hand-tb.webp",
      title: "Hand Tb",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "hand"],
      description: "Hand Tb, archived in the posters collection.",
      thumb: "assets/posters/hand-tb.webp",
      src: "assets/posters/hand-tb.webp"
    },
    {
      id: "posters-kane-webp",
      folder: "posters",
      file: "kane.webp",
      title: "Kane",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "kane"],
      description: "Kane, archived in the posters collection.",
      thumb: "assets/posters/kane.webp",
      src: "assets/posters/kane.webp"
    },
    {
      id: "posters-loa-1-webp",
      folder: "posters",
      file: "loa-1.webp",
      title: "Loa 1",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "loa"],
      description: "Loa 1, archived in the posters collection.",
      thumb: "assets/posters/loa-1.webp",
      src: "assets/posters/loa-1.webp"
    },
    {
      id: "posters-monster-munch-jpg",
      folder: "posters",
      file: "monster-munch.jpg",
      title: "Monster Munch",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "monster", "munch"],
      description: "Monster Munch, archived in the posters collection.",
      thumb: "assets/posters/monster-munch.jpg",
      src: "assets/posters/monster-munch.jpg"
    },
    {
      id: "posters-palms-intertwined-webp",
      folder: "posters",
      file: "palms-intertwined.webp",
      title: "Palms Intertwined",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "palms", "intertwined"],
      description: "Palms Intertwined, archived in the posters collection.",
      thumb: "assets/posters/palms-intertwined.webp",
      src: "assets/posters/palms-intertwined.webp"
    },
    {
      id: "posters-sarah-walker-webp",
      folder: "posters",
      file: "sarah-walker.webp",
      title: "Sarah Walker",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "sarah", "walker"],
      description: "Sarah Walker, archived in the posters collection.",
      thumb: "assets/posters/sarah-walker.webp",
      src: "assets/posters/sarah-walker.webp"
    },
    {
      id: "posters-solo-fel-card-webp",
      folder: "posters",
      file: "solo-fel-card.webp",
      title: "Solo Fel Card",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "solo", "fel", "card"],
      description: "Solo Fel Card, archived in the posters collection.",
      thumb: "assets/posters/solo-fel-card.webp",
      src: "assets/posters/solo-fel-card.webp"
    },
    {
      id: "posters-stars-texture3-webp",
      folder: "posters",
      file: "stars-texture3.webp",
      title: "Stars Texture3",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "stars", "texture3"],
      description: "Stars Texture3, archived in the posters collection.",
      thumb: "assets/posters/stars-texture3.webp",
      src: "assets/posters/stars-texture3.webp"
    },
    {
      id: "posters-thbs-png",
      folder: "posters",
      file: "thbs.png",
      title: "Thbs",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "thbs"],
      description: "Thbs, archived in the posters collection.",
      thumb: "assets/posters/thbs.png",
      src: "assets/posters/thbs.png"
    },
    {
      id: "posters-the-7th-dawn-webp",
      folder: "posters",
      file: "the-7th-dawn.webp",
      title: "The 7Th Dawn",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "the", "7th", "dawn"],
      description: "The 7Th Dawn, archived in the posters collection.",
      thumb: "assets/posters/the-7th-dawn.webp",
      src: "assets/posters/the-7th-dawn.webp"
    },
    {
      id: "posters-the-eye-jpg",
      folder: "posters",
      file: "the-eye.jpg",
      title: "The Eye",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "the", "eye"],
      description: "The Eye, archived in the posters collection.",
      thumb: "assets/posters/the-eye.jpg",
      src: "assets/posters/the-eye.jpg"
    },
    {
      id: "posters-vhd-webp",
      folder: "posters",
      file: "vhd.webp",
      title: "Vhd",
      year: "2026",
      kind: "Poster",
      medium: "Poster / Digital Design",
      tools: ["Digital"],
      tags: ["poster", "layout", "digital", "vhd"],
      description: "Vhd, archived in the posters collection.",
      thumb: "assets/posters/vhd.webp",
      src: "assets/posters/vhd.webp"
    },
    {
      id: "stable-diffusion-cap18-png",
      folder: "stable-diffusion",
      file: "cap18.png",
      title: "Cap18",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "cap18"],
      description: "Cap18, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/cap18.png",
      src: "assets/stable-diffusion/cap18.png"
    },
    {
      id: "stable-diffusion-cap28-png",
      folder: "stable-diffusion",
      file: "cap28.png",
      title: "Cap28",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "cap28"],
      description: "Cap28, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/cap28.png",
      src: "assets/stable-diffusion/cap28.png"
    },
    {
      id: "stable-diffusion-face-close-up-of-aqu-jpg",
      folder: "stable-diffusion",
      file: "face-close-up-of-aqu.jpg",
      title: "Face Close Up Of Aqu",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "face", "close", "aqu"],
      description: "Face Close Up Of Aqu, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/face-close-up-of-aqu.jpg",
      src: "assets/stable-diffusion/face-close-up-of-aqu.jpg"
    },
    {
      id: "stable-diffusion-face-close-up-of-bat-1-jpg",
      folder: "stable-diffusion",
      file: "face-close-up-of-bat-1.jpg",
      title: "Face Close Up Of Bat(1)",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "face", "close", "bat"],
      description: "Face Close Up Of Bat(1), archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/face-close-up-of-bat-1.jpg",
      src: "assets/stable-diffusion/face-close-up-of-bat-1.jpg"
    },
    {
      id: "stable-diffusion-face-close-up-of-sup-jpg",
      folder: "stable-diffusion",
      file: "face-close-up-of-sup.jpg",
      title: "Face Close Up Of Sup",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "face", "close", "sup"],
      description: "Face Close Up Of Sup, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/face-close-up-of-sup.jpg",
      src: "assets/stable-diffusion/face-close-up-of-sup.jpg"
    },
    {
      id: "stable-diffusion-gilgamesh-brush-transformed-upscayl-4x-realesrgan-x4plus-anime-jpeg",
      folder: "stable-diffusion",
      file: "gilgamesh-brush-transformed-upscayl-4x-realesrgan-x4plus-anime.jpeg",
      title: "Gilgamesh Brush Transformed Upscayl 4X Realesrgan X4plus Anime",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "gilgamesh", "brush", "transformed"],
      description: "Gilgamesh Brush Transformed Upscayl 4X Realesrgan X4plus Anime, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/gilgamesh-brush-transformed-upscayl-4x-realesrgan-x4plus-anime.jpeg",
      src: "assets/stable-diffusion/gilgamesh-brush-transformed-upscayl-4x-realesrgan-x4plus-anime.jpeg"
    },
    {
      id: "stable-diffusion-hen-jpg",
      folder: "stable-diffusion",
      file: "hen.jpg",
      title: "Hen",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "hen"],
      description: "Hen, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/hen.jpg",
      src: "assets/stable-diffusion/hen.jpg"
    },
    {
      id: "stable-diffusion-hero1-jpg",
      folder: "stable-diffusion",
      file: "hero1.jpg",
      title: "Hero1",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "hero1"],
      description: "Hero1, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/hero1.jpg",
      src: "assets/stable-diffusion/hero1.jpg"
    },
    {
      id: "stable-diffusion-hero3-jpg",
      folder: "stable-diffusion",
      file: "hero3.jpg",
      title: "Hero3",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "hero3"],
      description: "Hero3, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/hero3.jpg",
      src: "assets/stable-diffusion/hero3.jpg"
    },
    {
      id: "stable-diffusion-myth1-jpg",
      folder: "stable-diffusion",
      file: "myth1.jpg",
      title: "Myth1",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "myth1"],
      description: "Myth1, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/myth1.jpg",
      src: "assets/stable-diffusion/myth1.jpg"
    },
    {
      id: "stable-diffusion-myth2-jpg",
      folder: "stable-diffusion",
      file: "myth2.jpg",
      title: "Myth2",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "myth2"],
      description: "Myth2, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/myth2.jpg",
      src: "assets/stable-diffusion/myth2.jpg"
    },
    {
      id: "stable-diffusion-nov-1-jpg",
      folder: "stable-diffusion",
      file: "nov-1.jpg",
      title: "Nov 1",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "nov"],
      description: "Nov 1, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/nov-1.jpg",
      src: "assets/stable-diffusion/nov-1.jpg"
    },
    {
      id: "stable-diffusion-nov-2-jpg",
      folder: "stable-diffusion",
      file: "nov-2.jpg",
      title: "Nov 2",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "nov"],
      description: "Nov 2, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/nov-2.jpg",
      src: "assets/stable-diffusion/nov-2.jpg"
    },
    {
      id: "stable-diffusion-nov-3-jpg",
      folder: "stable-diffusion",
      file: "nov-3.jpg",
      title: "Nov 3",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "nov"],
      description: "Nov 3, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/nov-3.jpg",
      src: "assets/stable-diffusion/nov-3.jpg"
    },
    {
      id: "stable-diffusion-nov-4-png",
      folder: "stable-diffusion",
      file: "nov-4.png",
      title: "Nov 4",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "nov"],
      description: "Nov 4, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/nov-4.png",
      src: "assets/stable-diffusion/nov-4.png"
    },
    {
      id: "stable-diffusion-sf2-jpg",
      folder: "stable-diffusion",
      file: "sf2.jpg",
      title: "Sf2",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "sf2"],
      description: "Sf2, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/sf2.jpg",
      src: "assets/stable-diffusion/sf2.jpg"
    },
    {
      id: "stable-diffusion-sf3-jpg",
      folder: "stable-diffusion",
      file: "sf3.jpg",
      title: "Sf3",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "sf3"],
      description: "Sf3, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/sf3.jpg",
      src: "assets/stable-diffusion/sf3.jpg"
    },
    {
      id: "stable-diffusion-supe18-jpg",
      folder: "stable-diffusion",
      file: "supe18.jpg",
      title: "Supe18",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "supe18"],
      description: "Supe18, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/supe18.jpg",
      src: "assets/stable-diffusion/supe18.jpg"
    },
    {
      id: "stable-diffusion-thor-jpeg",
      folder: "stable-diffusion",
      file: "thor.jpeg",
      title: "Thor",
      year: "2026",
      kind: "AI Study",
      medium: "AI Image / Digital Study",
      tools: ["Digital"],
      tags: ["ai", "study", "image", "thor"],
      description: "Thor, archived in the stable diffusion collection.",
      thumb: "assets/stable-diffusion/thor.jpeg",
      src: "assets/stable-diffusion/thor.jpeg"
    }
  ]
};
